In [16]:
import pandas as pd
from pathlib import Path

In [17]:
def load_results_table(results_dir, methods_list, use_coords, use_demographic, file_name="aggregated_results.json"):
    agg_list = []
    for method in methods_list:
        if use_demographic and use_coords:
            folder_name = f"{method}_coords_demographic_radiomics"
        elif use_demographic and not use_coords:
            folder_name = f"{method}_demographic_radiomics"
        elif not use_demographic and use_coords:
            folder_name = f"{method}_coords_radiomics"
        else:
            folder_name = f"{method}_radiomics"
        aggregated_result_dir = Path(results_dir)/folder_name / file_name
        df = pd.read_json(aggregated_result_dir)
        agg_list.append(df)
    final_df = pd.concat(agg_list, ignore_index=True)
    # final_df = final_df[['model', 'Accuracy_Mean', 'ROC_AUC_Mean']]
    display(final_df)
    print("Average across models:")
    display(pd.DataFrame(final_df.mean(numeric_only=True)).T)

# Five Fold Cross Validation for Center 1 Dataset

In [18]:
models = ["transformer", "deep_sets", "mil", "graph", "set_transformer", 'ml_models']

In [19]:
print("Radiomics Features:")
load_results_table("../Results", models, use_coords=False, use_demographic=False)

Radiomics Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.730931,0.051506,0.749828,0.106449,0.725214,0.060542,0.870588,0.076696,0.542857,0.176485,0.787670,0.029292
1,deep_sets,0.718257,0.064060,0.755376,0.112422,0.708543,0.060575,0.870588,0.064438,0.514286,0.146854,0.779460,0.046493
2,mil,0.738027,0.074609,0.743428,0.053060,0.718398,0.056684,0.894118,0.049215,0.529487,0.119375,0.796440,0.053100
3,graph,0.664220,0.026115,0.679778,0.067355,0.710920,0.074173,0.741176,0.169469,0.549634,0.266263,0.709931,0.049265
4,set_transformer,0.684664,0.035563,0.764006,0.039059,0.689454,0.041751,0.823529,0.058824,0.499817,0.116851,0.748627,0.025875
5,AdaBoost,0.711806,0.053856,0.733495,0.055703,0.681205,0.051077,0.941176,0.041595,0.404945,0.152294,0.789064,0.034639
6,CatBoost,0.732265,0.033165,0.747641,0.053852,0.716270,0.039732,0.882353,0.072044,0.532051,0.090200,0.789012,0.033404
7,Extra Trees,0.704694,0.071891,0.762465,0.065057,0.715542,0.051084,0.800000,0.114668,0.580769,0.064994,0.753192,0.070119
8,Gradient Boosting,0.697353,0.038930,0.728992,0.057585,0.714912,0.036957,0.788235,0.052613,0.576007,0.101289,0.748379,0.027347
9,Logistic Regression,0.717827,0.057041,0.709179,0.048109,0.704423,0.031278,0.870588,0.105227,0.514286,0.072334,0.776963,0.053541
10,MLP,0.717597,0.058170,0.759244,0.122494,0.747584,0.036636,0.764706,0.117647,0.658059,0.055679,0.752534,0.063542
11,Random Forest,0.691576,0.022112,0.770567,0.045122,0.719849,0.029532,0.752941,0.026307,0.610440,0.036970,0.735705,0.022442
12,SVM (RBF kernel),0.677783,0.069568,0.666634,0.039277,0.651878,0.055384,0.952941,0.064438,0.312271,0.171233,0.772262,0.042387
13,TabPFN,0.704019,0.049147,0.777548,0.051577,0.733999,0.045423,0.764706,0.117647,0.628205,0.096899,0.744343,0.051412
14,XGBoost,0.691806,0.038026,0.696084,0.072852,0.683305,0.049050,0.870588,0.105227,0.456044,0.131588,0.761614,0.038189
15,k-Nearest Neighbors,0.710011,0.106683,0.737648,0.101850,0.717815,0.082176,0.823529,0.124784,0.561722,0.163229,0.763511,0.087350
16,lightGBM,0.691806,0.074100,0.695400,0.086273,0.678852,0.073398,0.894118,0.064438,0.421612,0.194762,0.769107,0.049229

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.704979,0.054385,0.733959,0.0693,0.706951,0.051497,0.841522,0.08384,0.523088,0.1269,0.763401,0.045743

In [20]:
print("Radiomics + demographic Features:")
load_results_table("../Results", models, use_coords=False, use_demographic=True)

Radiomics + demographic Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.751175,0.053519,0.866042,0.031472,0.773856,0.046742,0.800000,0.067069,0.686630,0.078077,0.785600,0.046749
1,deep_sets,0.764279,0.071133,0.837169,0.045909,0.761297,0.054570,0.858824,0.078920,0.635348,0.108717,0.806100,0.056769
2,mil,0.784509,0.043070,0.860924,0.028981,0.773158,0.027875,0.882353,0.041595,0.653114,0.064329,0.824024,0.032228
3,graph,0.764509,0.037601,0.837384,0.055339,0.786954,0.061284,0.823529,0.110049,0.680220,0.166991,0.798076,0.038938
4,set_transformer,0.784954,0.031897,0.847662,0.056058,0.791095,0.050796,0.858824,0.089210,0.683883,0.151054,0.819564,0.026967
5,AdaBoost,0.703789,0.044520,0.859971,0.051484,0.688395,0.022941,0.882353,0.072044,0.466667,0.079342,0.772339,0.034766
6,CatBoost,0.751376,0.052425,0.852510,0.040578,0.766196,0.095841,0.847059,0.121979,0.628205,0.192788,0.794099,0.042386
7,Extra Trees,0.717812,0.040054,0.822527,0.034088,0.723248,0.031773,0.823529,0.093008,0.579487,0.075521,0.767631,0.041388
8,Gradient Boosting,0.750931,0.055031,0.848707,0.035906,0.776354,0.060033,0.800000,0.067069,0.686447,0.110638,0.785987,0.044763
9,Logistic Regression,0.712050,0.071059,0.704837,0.041661,0.701717,0.047248,0.858824,0.098431,0.517949,0.061718,0.771163,0.062495
10,MLP,0.757842,0.066165,0.833635,0.082794,0.769058,0.039773,0.823529,0.117647,0.672344,0.059813,0.792719,0.063740
11,Random Forest,0.743604,0.062256,0.829401,0.037852,0.769608,0.041175,0.788235,0.067069,0.684066,0.072315,0.778396,0.051797
12,SVM (RBF kernel),0.677783,0.069568,0.666634,0.039277,0.651878,0.055384,0.952941,0.064438,0.312271,0.171233,0.772262,0.042387
13,TabPFN,0.738057,0.029125,0.840826,0.014883,0.768365,0.029073,0.776471,0.049215,0.687729,0.050698,0.771527,0.027938
14,XGBoost,0.703804,0.049424,0.828690,0.082439,0.697571,0.048686,0.870588,0.113149,0.480952,0.190483,0.769366,0.038279
15,k-Nearest Neighbors,0.710011,0.106683,0.737648,0.101850,0.717815,0.082176,0.823529,0.124784,0.561722,0.163229,0.763511,0.087350
16,lightGBM,0.657093,0.042937,0.794990,0.063197,0.676302,0.016380,0.764706,0.083189,0.514286,0.041953,0.716591,0.043877

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.73374,0.054498,0.815856,0.049633,0.740757,0.04775,0.83737,0.085816,0.59596,0.108171,0.781703,0.046048

In [21]:
print("Radiomics + coords Features:")
load_results_table("../Results", models, use_coords=True, use_demographic=False)

Radiomics + coords Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.812095,0.038685,0.882030,0.032446,0.803455,0.052985,0.894118,0.049215,0.705495,0.092136,0.844741,0.029934
1,deep_sets,0.791850,0.044612,0.860978,0.056399,0.775813,0.062421,0.905882,0.032219,0.639927,0.146728,0.833626,0.024540
2,mil,0.791175,0.059368,0.835725,0.073761,0.775873,0.042286,0.894118,0.076696,0.654212,0.078831,0.829815,0.049596
3,graph,0.751850,0.068212,0.776708,0.111931,0.751767,0.056106,0.847059,0.128876,0.623443,0.126449,0.792722,0.070977
4,set_transformer,0.737582,0.054159,0.808576,0.032021,0.746283,0.042936,0.823529,0.093008,0.624542,0.082517,0.780624,0.048748
5,AdaBoost,0.738717,0.052929,0.765961,0.053229,0.702363,0.057557,0.952941,0.026307,0.453663,0.147989,0.807210,0.033222
6,CatBoost,0.745384,0.054166,0.792071,0.032646,0.732212,0.072979,0.894118,0.064438,0.546154,0.195455,0.801309,0.033169
7,Extra Trees,0.738717,0.056922,0.800776,0.026615,0.741995,0.054764,0.835294,0.087249,0.612821,0.090041,0.783705,0.053145
8,Gradient Boosting,0.744279,0.048777,0.766537,0.016398,0.759264,0.059600,0.823529,0.117647,0.643956,0.121077,0.784168,0.046812
9,Logistic Regression,0.704709,0.049080,0.696208,0.065947,0.695332,0.029534,0.858824,0.098431,0.498901,0.074067,0.766707,0.047707
10,MLP,0.764294,0.073280,0.813629,0.098876,0.781628,0.059882,0.823529,0.124784,0.689011,0.105644,0.797057,0.068676
11,Random Forest,0.731591,0.053238,0.794877,0.046060,0.760117,0.042118,0.776471,0.096657,0.673260,0.070763,0.765518,0.055209
12,SVM (RBF kernel),0.677783,0.069568,0.666634,0.039277,0.651878,0.055384,0.952941,0.064438,0.312271,0.171233,0.772262,0.042387
13,TabPFN,0.757167,0.101262,0.838979,0.064008,0.754967,0.063728,0.847059,0.121979,0.637729,0.085361,0.797520,0.089292
14,XGBoost,0.698702,0.086459,0.754552,0.063431,0.679372,0.072672,0.905882,0.114668,0.422711,0.181925,0.773233,0.071760
15,k-Nearest Neighbors,0.710011,0.106683,0.737648,0.101850,0.717815,0.082176,0.823529,0.124784,0.561722,0.163229,0.763511,0.087350
16,lightGBM,0.725384,0.062208,0.774504,0.065975,0.700293,0.060324,0.917647,0.067069,0.469048,0.152928,0.792473,0.046074

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.742429,0.063506,0.786258,0.057698,0.737084,0.056909,0.869204,0.087557,0.574639,0.122728,0.793306,0.052859

In [22]:
print("Radiomics + coords + demographic Features:")
load_results_table("../Results", models, use_coords=True, use_demographic=True)

Radiomics + coords + demographic Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.818547,0.040170,0.910149,0.052559,0.793397,0.053054,0.929412,0.049215,0.672344,0.102577,0.854386,0.028481
1,deep_sets,0.825643,0.048212,0.909966,0.047602,0.833889,0.042781,0.870588,0.096657,0.768498,0.065482,0.848954,0.047101
2,mil,0.811405,0.059006,0.903351,0.056494,0.800496,0.031636,0.894118,0.105227,0.703114,0.062688,0.842385,0.053786
3,graph,0.840341,0.071940,0.887535,0.069635,0.860410,0.104882,0.870588,0.076696,0.803114,0.154870,0.861640,0.064136
4,set_transformer,0.818087,0.079479,0.878518,0.063525,0.810693,0.067945,0.894118,0.064438,0.714835,0.132445,0.849641,0.061613
5,AdaBoost,0.731146,0.028078,0.858500,0.050337,0.706663,0.017885,0.905882,0.032219,0.498718,0.049736,0.793738,0.018662
6,CatBoost,0.737382,0.048680,0.850022,0.035065,0.743099,0.035016,0.835294,0.127526,0.608059,0.120516,0.781090,0.053678
7,Extra Trees,0.738042,0.044905,0.848018,0.025546,0.741511,0.032704,0.835294,0.105227,0.612821,0.068082,0.782447,0.046869
8,Gradient Boosting,0.750486,0.062499,0.849957,0.038746,0.779333,0.044387,0.788235,0.078920,0.700733,0.076769,0.782549,0.053619
9,Logistic Regression,0.704709,0.049080,0.698761,0.037742,0.691605,0.027660,0.870588,0.105227,0.484615,0.062578,0.768812,0.049173
10,MLP,0.778072,0.040674,0.855365,0.073895,0.811096,0.065672,0.811765,0.113149,0.737729,0.111524,0.804495,0.043504
11,Random Forest,0.751376,0.032292,0.847382,0.017884,0.783004,0.044323,0.788235,0.067069,0.705311,0.086004,0.783118,0.027982
12,SVM (RBF kernel),0.677783,0.069568,0.666634,0.039277,0.651878,0.055384,0.952941,0.064438,0.312271,0.171233,0.772262,0.042387
13,TabPFN,0.784968,0.052401,0.871752,0.037455,0.797255,0.032087,0.835294,0.076696,0.717399,0.048895,0.814990,0.048462
14,XGBoost,0.703804,0.049424,0.827850,0.082552,0.697571,0.048686,0.870588,0.113149,0.480952,0.190483,0.769366,0.038279
15,k-Nearest Neighbors,0.710011,0.106683,0.737648,0.101850,0.717815,0.082176,0.823529,0.124784,0.561722,0.163229,0.763511,0.087350
16,lightGBM,0.656878,0.037412,0.802316,0.049639,0.673509,0.019122,0.776471,0.049215,0.497619,0.061190,0.720848,0.027887

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.755216,0.054147,0.835513,0.051753,0.758425,0.047377,0.856055,0.085285,0.622344,0.101665,0.799661,0.046645

# Second dataset

In [23]:
print("Radiomics Features:")
load_results_table("../Results", models, use_coords=False, use_demographic=False, file_name="center2_aggregated_results.json")

Radiomics Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.6225,0.056181,0.655303,0.039032,0.574003,0.050324,0.672222,0.238469,0.581818,0.200464,0.597961,0.129062
1,deep_sets,0.5400,0.027099,0.580871,0.062035,0.470926,0.053483,0.377778,0.309694,0.672727,0.225905,0.372665,0.202704
2,mil,0.5725,0.066965,0.602652,0.075787,0.498625,0.088716,0.350000,0.295674,0.754545,0.128966,0.377672,0.215320
3,graph,0.5475,0.065192,0.586995,0.080418,0.491295,0.071620,0.511111,0.380160,0.577273,0.339619,0.450785,0.195758
4,set_transformer,0.5675,0.045586,0.617677,0.061663,0.504111,0.079855,0.338889,0.248762,0.754545,0.131936,0.375568,0.193828
5,AdaBoost,0.6325,0.014252,0.666856,0.014246,0.554565,0.009897,0.933333,0.024845,0.386364,0.027835,0.695623,0.011346
6,CatBoost,0.6500,0.008839,0.682576,0.019552,0.569407,0.005377,0.911111,0.023241,0.436364,0.010164,0.700774,0.010176
7,Extra Trees,0.6325,0.033773,0.670455,0.027101,0.579592,0.036974,0.683333,0.072436,0.590909,0.077072,0.625233,0.034114
8,Gradient Boosting,0.6225,0.041833,0.636111,0.044582,0.564597,0.036446,0.716667,0.104675,0.545455,0.083505,0.628857,0.048398
9,Logistic Regression,0.5825,0.020917,0.641414,0.022280,0.523748,0.015508,0.827778,0.124846,0.381818,0.110642,0.638230,0.037534
10,MLP,0.5875,0.045928,0.642109,0.039201,0.523787,0.052200,0.522222,0.294235,0.640909,0.161827,0.494364,0.193292
11,Random Forest,0.6275,0.025617,0.675505,0.015888,0.568471,0.023643,0.722222,0.051967,0.550000,0.054261,0.635310,0.026044
12,SVM (RBF kernel),0.6250,0.012500,0.726389,0.000720,0.548501,0.008847,0.944444,0.000000,0.363636,0.022727,0.693935,0.007081
13,TabPFN,0.5325,0.028777,0.643813,0.028724,0.462742,0.062419,0.261111,0.099381,0.754545,0.082572,0.326706,0.090136
14,XGBoost,0.6350,0.024044,0.683649,0.041491,0.558552,0.018014,0.905556,0.037268,0.413636,0.043717,0.690651,0.019071
15,k-Nearest Neighbors,0.6350,0.024044,0.661679,0.013893,0.564548,0.018629,0.827778,0.041201,0.477273,0.035935,0.671014,0.022718
16,lightGBM,0.6175,0.031375,0.652525,0.041358,0.547740,0.023837,0.883333,0.069166,0.400000,0.084428,0.674822,0.022972

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.601765,0.033701,0.648622,0.03694,0.535601,0.038576,0.669935,0.142119,0.545989,0.107152,0.567657,0.085856

In [24]:
print("Radiomics + demographic Features:")
load_results_table("../Results", models, use_coords=False, use_demographic=True, file_name="center2_aggregated_results.json")

Radiomics + demographic Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.6625,0.063738,0.787879,0.063895,0.716765,0.116798,0.433333,0.298272,0.850000,0.151269,0.492864,0.206395
1,deep_sets,0.6225,0.085422,0.639899,0.109195,0.697357,0.184888,0.333333,0.254588,0.859091,0.090053,0.402710,0.221900
2,mil,0.6300,0.041079,0.699495,0.088585,0.708459,0.059085,0.333333,0.208796,0.872727,0.099845,0.414759,0.190687
3,graph,0.5900,0.128817,0.685101,0.160145,0.602083,0.161705,0.455556,0.202797,0.700000,0.241808,0.488835,0.141545
4,set_transformer,0.6625,0.081968,0.739015,0.082928,0.751049,0.100578,0.400000,0.291733,0.877273,0.127151,0.469295,0.229095
5,AdaBoost,0.6800,0.040117,0.848485,0.018604,0.598411,0.042855,0.905556,0.046481,0.495455,0.100874,0.718797,0.020985
6,CatBoost,0.7125,0.058630,0.847980,0.006950,0.644023,0.089592,0.866667,0.060221,0.586364,0.151950,0.733094,0.032442
7,Extra Trees,0.7175,0.040117,0.769949,0.024966,0.661511,0.043906,0.766667,0.046481,0.677273,0.054261,0.709651,0.038941
8,Gradient Boosting,0.6650,0.084502,0.797096,0.058501,0.604114,0.075193,0.822222,0.063949,0.536364,0.194580,0.691593,0.040748
9,Logistic Regression,0.5875,0.023385,0.634722,0.030279,0.527023,0.018908,0.838889,0.133795,0.381818,0.115216,0.643713,0.041755
10,MLP,0.6350,0.077762,0.671402,0.060740,0.605503,0.097868,0.444444,0.237333,0.790909,0.067036,0.493691,0.204780
11,Random Forest,0.7000,0.017678,0.796023,0.021898,0.638411,0.019592,0.772222,0.053432,0.640909,0.043717,0.697987,0.022254
12,SVM (RBF kernel),0.6250,0.012500,0.726389,0.000720,0.548501,0.008847,0.944444,0.000000,0.363636,0.022727,0.693935,0.007081
13,TabPFN,0.7925,0.016771,0.858460,0.010203,0.850573,0.023670,0.655556,0.057601,0.904545,0.024896,0.738723,0.031922
14,XGBoost,0.6850,0.052589,0.844571,0.027971,0.608988,0.052154,0.872222,0.063949,0.531818,0.124067,0.714573,0.032403
15,k-Nearest Neighbors,0.6350,0.024044,0.661679,0.013893,0.564548,0.018629,0.827778,0.041201,0.477273,0.035935,0.671014,0.022718
16,lightGBM,0.6900,0.035795,0.822664,0.018055,0.614197,0.044961,0.866667,0.066319,0.545455,0.111340,0.716001,0.015300

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.664265,0.052054,0.754753,0.046913,0.643619,0.06819,0.678758,0.125115,0.652406,0.103337,0.617131,0.088291

In [25]:
print("Radiomics + coords Features:")
load_results_table("../Results", models, use_coords=True, use_demographic=False, file_name="center2_aggregated_results.json")

Radiomics + coords Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.6200,0.056319,0.708712,0.029964,0.620557,0.060662,0.377778,0.197007,0.818182,0.075378,0.449913,0.162248
1,deep_sets,0.5400,0.047104,0.534154,0.065503,0.403008,0.163022,0.194444,0.235702,0.822727,0.119615,0.232597,0.205833
2,mil,0.6150,0.058229,0.635101,0.117669,0.592382,0.056878,0.405556,0.364620,0.786364,0.199819,0.409091,0.276135
3,graph,0.6325,0.059029,0.670328,0.038707,0.621930,0.089019,0.511111,0.151637,0.731818,0.116332,0.546819,0.102652
4,set_transformer,0.6300,0.027386,0.665278,0.016501,0.608343,0.027304,0.511111,0.186959,0.727273,0.122390,0.539745,0.108492
5,AdaBoost,0.6400,0.010458,0.728030,0.037399,0.560915,0.007955,0.922222,0.030429,0.409091,0.027835,0.697380,0.010281
6,CatBoost,0.6600,0.010458,0.710606,0.016599,0.578258,0.009891,0.905556,0.015215,0.459091,0.029633,0.705668,0.004370
7,Extra Trees,0.6375,0.061872,0.675189,0.034425,0.578940,0.053737,0.683333,0.138332,0.600000,0.034468,0.624800,0.087091
8,Gradient Boosting,0.6775,0.043661,0.715278,0.043331,0.617193,0.041489,0.750000,0.073493,0.618182,0.058828,0.676093,0.045931
9,Logistic Regression,0.5825,0.030104,0.644444,0.019826,0.523148,0.022542,0.844444,0.112148,0.368182,0.103403,0.643508,0.038534
10,MLP,0.5950,0.040117,0.646780,0.040684,0.562071,0.062783,0.461111,0.166203,0.704545,0.105382,0.493524,0.110626
11,Random Forest,0.6625,0.023385,0.694318,0.011470,0.607984,0.038627,0.727778,0.090863,0.609091,0.094257,0.658517,0.027819
12,SVM (RBF kernel),0.6250,0.012500,0.726389,0.000720,0.548501,0.008847,0.944444,0.000000,0.363636,0.022727,0.693935,0.007081
13,TabPFN,0.6050,0.060338,0.686048,0.013845,0.580382,0.075729,0.361111,0.178946,0.804545,0.052322,0.432618,0.162936
14,XGBoost,0.6500,0.043301,0.731124,0.055850,0.572059,0.033670,0.894444,0.041201,0.450000,0.070784,0.697342,0.031717
15,k-Nearest Neighbors,0.6350,0.024044,0.661679,0.013893,0.564548,0.018629,0.827778,0.041201,0.477273,0.035935,0.671014,0.022718
16,lightGBM,0.6475,0.047104,0.728283,0.023262,0.570130,0.036934,0.905556,0.037268,0.436364,0.092876,0.698798,0.028137

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.626765,0.038553,0.680102,0.034097,0.571197,0.047513,0.660458,0.121248,0.599198,0.080117,0.580668,0.084271

In [26]:
print("Radiomics + demographic + coords Features:")
load_results_table("../Results", models, use_coords=True, use_demographic=True, file_name="center2_aggregated_results.json")

Radiomics + demographic + coords Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.7075,0.104058,0.811364,0.050663,0.697839,0.095705,0.583333,0.329257,0.809091,0.102399,0.600086,0.231036
1,deep_sets,0.6775,0.063982,0.753030,0.058514,0.724917,0.117390,0.538889,0.203746,0.790909,0.206681,0.586087,0.114762
2,mil,0.6700,0.097066,0.741793,0.135507,0.672024,0.201420,0.411111,0.274565,0.881818,0.080993,0.481845,0.274687
3,graph,0.7150,0.055481,0.794634,0.048394,0.760849,0.054786,0.527778,0.111111,0.868182,0.019015,0.620560,0.094775
4,set_transformer,0.6575,0.071589,0.768056,0.046046,0.669068,0.076376,0.466667,0.319384,0.813636,0.142295,0.502962,0.219478
5,AdaBoost,0.6725,0.037914,0.854167,0.015291,0.591259,0.039858,0.911111,0.045644,0.477273,0.102902,0.715307,0.015969
6,CatBoost,0.7175,0.011180,0.843687,0.015228,0.638336,0.021370,0.866667,0.069166,0.595455,0.060984,0.733418,0.017570
7,Extra Trees,0.6975,0.035795,0.782702,0.031902,0.645241,0.040502,0.738889,0.063949,0.663636,0.074343,0.687036,0.033237
8,Gradient Boosting,0.7325,0.064711,0.825000,0.057022,0.685996,0.076818,0.772222,0.077080,0.700000,0.121755,0.722924,0.056595
9,Logistic Regression,0.5875,0.025000,0.632955,0.030573,0.527923,0.019373,0.844444,0.113855,0.377273,0.120904,0.646360,0.028517
10,MLP,0.6625,0.019764,0.739078,0.027804,0.605622,0.035709,0.744444,0.129398,0.595455,0.105871,0.661231,0.045005
11,Random Forest,0.7250,0.008839,0.817740,0.012706,0.663708,0.018796,0.794444,0.080027,0.668182,0.057045,0.720946,0.024572
12,SVM (RBF kernel),0.6250,0.012500,0.726389,0.000720,0.548501,0.008847,0.944444,0.000000,0.363636,0.022727,0.693935,0.007081
13,TabPFN,0.7825,0.024367,0.833838,0.027990,0.792101,0.016372,0.700000,0.056928,0.850000,0.012448,0.742445,0.036917
14,XGBoost,0.6850,0.052589,0.845960,0.027680,0.608988,0.052154,0.872222,0.063949,0.531818,0.124067,0.714573,0.032403
15,k-Nearest Neighbors,0.6350,0.024044,0.661679,0.013893,0.564548,0.018629,0.827778,0.041201,0.477273,0.035935,0.671014,0.022718
16,lightGBM,0.7025,0.040889,0.831755,0.015107,0.624837,0.041732,0.866667,0.030429,0.568182,0.095075,0.724814,0.021927

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.685441,0.044104,0.780225,0.036179,0.648339,0.055049,0.730065,0.118217,0.64893,0.087379,0.660326,0.075132

# Test Time Adaptation (TTA) on Center 2 data

## TENT method for TTA

In [30]:
print("Radiomics + demographic + coords Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", 'set_transformer'], use_coords=True, use_demographic=True, file_name="tta_tent_center2_aggregated_results.json")

Radiomics + demographic + coords Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.7100,0.018540,0.868308,0.011577,0.614643,0.016645,0.955556,0.015215,0.509091,0.034468,0.747947,0.012873
1,mil,0.7700,0.027386,0.864141,0.011713,0.679620,0.028482,0.927778,0.015215,0.640909,0.043717,0.784338,0.022098
2,deep_sets,0.7725,0.016298,0.857702,0.006570,0.712113,0.026115,0.833333,0.043921,0.722727,0.040656,0.767066,0.017343
3,graph,0.6900,0.034686,0.791162,0.044891,0.618934,0.043684,0.844444,0.113855,0.563636,0.127961,0.708932,0.030046
4,set_transformer,0.7050,0.022707,0.810480,0.017730,0.611102,0.018840,0.950000,0.012423,0.504545,0.037345,0.743653,0.015942

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.7295,0.023924,0.838359,0.018496,0.647282,0.026753,0.902222,0.040125,0.588182,0.056829,0.750387,0.01966

## Norm method for TTA

In [33]:
print("Radiomics + demographic + coords Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", 'set_transformer'], use_coords=True, use_demographic=True, file_name="tta_norm_center2_aggregated_results.json")

Radiomics + demographic + coords Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.7075,0.104058,0.811364,0.050663,0.697839,0.095705,0.583333,0.329257,0.809091,0.102399,0.600086,0.231036
1,mil,0.6700,0.097066,0.741793,0.135507,0.672024,0.201420,0.411111,0.274565,0.881818,0.080993,0.481845,0.274687
2,deep_sets,0.6775,0.063982,0.753030,0.058514,0.724917,0.117390,0.538889,0.203746,0.790909,0.206681,0.586087,0.114762
3,graph,0.7150,0.055481,0.794634,0.048394,0.760849,0.054786,0.527778,0.111111,0.868182,0.019015,0.620560,0.094775
4,set_transformer,0.6575,0.071589,0.768056,0.046046,0.669068,0.076376,0.466667,0.319384,0.813636,0.142295,0.502962,0.219478

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.6855,0.078435,0.773775,0.067825,0.704939,0.109136,0.505556,0.247613,0.832727,0.110277,0.558308,0.186947

In [35]:
print("Radiomics + demographic  Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph"], use_coords=False, use_demographic=True, file_name="tta_tent_center2_aggregated_results.json")

Radiomics + demographic  Features:

,model,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,transformer,0.7050,0.014252,0.871086,0.015226,0.608660,0.012751,0.966667,0.012423,0.490909,0.030492,0.746865,0.008750
1,mil,0.7550,0.022707,0.857828,0.016233,0.661528,0.027705,0.938889,0.023241,0.604545,0.057045,0.775566,0.013335
2,deep_sets,0.7375,0.063738,0.830934,0.051693,0.658312,0.059301,0.877778,0.054149,0.622727,0.091757,0.751549,0.053619
3,graph,0.6800,0.078859,0.773990,0.088026,0.617854,0.094813,0.822222,0.149071,0.563636,0.168090,0.696999,0.073138

Average across models:

,Accuracy_Mean,Accuracy_STD,ROC_AUC_Mean,ROC_AUC_STD,Precision_Mean,Precision_STD,Recall_Mean,Recall_STD,Specificity_Mean,Specificity_STD,F1_Score_Mean,F1_Score_STD
0,0.719375,0.044889,0.83346,0.042795,0.636588,0.048643,0.901389,0.059721,0.570455,0.086846,0.742745,0.037211