In [70]:
import pandas as pd
from pathlib import Path

In [71]:
def load_results_table(results_dir, methods_list, use_coords, use_demographic, file_name="aggregated_results.json"):
    agg_list = []
    for method in methods_list:
        if use_demographic and use_coords:
            folder_name = f"{method}_coords_demographic_radiomics"
        elif use_demographic and not use_coords:
            folder_name = f"{method}_demographic_radiomics"
        elif not use_demographic and use_coords:
            folder_name = f"{method}_coords_radiomics"
        else:
            folder_name = f"{method}_radiomics"
        aggregated_result_dir = Path(results_dir)/folder_name / file_name
        df = pd.read_json(aggregated_result_dir)
        agg_list.append(df)
    final_df = pd.concat(agg_list, ignore_index=True)
    final_df = final_df[['model', 'Accuracy_Mean', 'ROC_AUC_Mean']]
    display(final_df)
    print("Average across models:")
    display(pd.DataFrame(final_df.mean(numeric_only=True)).T)

# Five Fold Cross Validation for Center 1 Dataset

In [72]:
print("Radiomics Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=False, use_demographic=False)

Radiomics Features:

                  model  Accuracy_Mean  ROC_AUC_Mean
0           transformer       0.730931      0.749828
1                   mil       0.738027      0.743428
2             deep_sets       0.718257      0.755376
3                 graph       0.663990      0.670513
4              AdaBoost       0.711806      0.733495
5              CatBoost       0.732265      0.747641
6           Extra Trees       0.704694      0.762465
7     Gradient Boosting       0.697353      0.728992
8   Logistic Regression       0.717827      0.709179
9                   MLP       0.717597      0.759244
10        Random Forest       0.691576      0.770567
11     SVM (RBF kernel)       0.677783      0.666634
12              XGBoost       0.691806      0.696084
13  k-Nearest Neighbors       0.710011      0.737648
14             lightGBM       0.691806      0.695400

Average across models:

   Accuracy_Mean  ROC_AUC_Mean
0       0.706382      0.728433

In [73]:
print("Radiomics + demographic Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=False, use_demographic=True)

Radiomics + demographic Features:

                  model  Accuracy_Mean  ROC_AUC_Mean
0           transformer       0.751175      0.866042
1                   mil       0.784509      0.860924
2             deep_sets       0.764279      0.837169
3                 graph       0.770945      0.821989
4              AdaBoost       0.703789      0.859971
5              CatBoost       0.751376      0.852510
6           Extra Trees       0.717812      0.822527
7     Gradient Boosting       0.750931      0.848707
8   Logistic Regression       0.712050      0.704837
9                   MLP       0.757842      0.833635
10        Random Forest       0.743604      0.829401
11     SVM (RBF kernel)       0.677783      0.666634
12              XGBoost       0.703804      0.828690
13  k-Nearest Neighbors       0.710011      0.737648
14             lightGBM       0.657093      0.794990

Average across models:

   Accuracy_Mean  ROC_AUC_Mean
0       0.730467      0.811045

In [74]:
print("Radiomics + coords Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=True, use_demographic=False)

Radiomics + coords Features:

                  model  Accuracy_Mean  ROC_AUC_Mean
0           transformer       0.812095      0.882030
1                   mil       0.791175      0.835725
2             deep_sets       0.791850      0.860978
3                 graph       0.704939      0.760493
4              AdaBoost       0.738717      0.765961
5              CatBoost       0.745384      0.792071
6           Extra Trees       0.738717      0.800776
7     Gradient Boosting       0.744279      0.766537
8   Logistic Regression       0.704709      0.696208
9                   MLP       0.764294      0.813629
10        Random Forest       0.731591      0.794877
11     SVM (RBF kernel)       0.677783      0.666634
12              XGBoost       0.698702      0.754552
13  k-Nearest Neighbors       0.710011      0.737648
14             lightGBM       0.725384      0.774504

Average across models:

   Accuracy_Mean  ROC_AUC_Mean
0       0.738642      0.780175

In [75]:
print("Radiomics + coords + demographic Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=True, use_demographic=True)

Radiomics + coords + demographic Features:

                  model  Accuracy_Mean  ROC_AUC_Mean
0           transformer       0.818547      0.910149
1                   mil       0.811405      0.903351
2             deep_sets       0.825643      0.909966
3                 graph       0.832584      0.889614
4              AdaBoost       0.731146      0.858500
5              CatBoost       0.737382      0.850022
6           Extra Trees       0.738042      0.848018
7     Gradient Boosting       0.750486      0.849957
8   Logistic Regression       0.704709      0.698761
9                   MLP       0.778072      0.855365
10        Random Forest       0.751376      0.847382
11     SVM (RBF kernel)       0.677783      0.666634
12              XGBoost       0.703804      0.827850
13  k-Nearest Neighbors       0.710011      0.737648
14             lightGBM       0.656878      0.802316

Average across models:

   Accuracy_Mean  ROC_AUC_Mean
0       0.748525      0.830369

# Second dataset

In [76]:
print("Radiomics Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=False, use_demographic=False, file_name="center2_aggregated_results.json")

Radiomics Features:

                  model  Accuracy_Mean  ROC_AUC_Mean
0           transformer         0.6225      0.655303
1                   mil         0.5725      0.602652
2             deep_sets         0.5400      0.580871
3                 graph         0.5350      0.588005
4              AdaBoost         0.6325      0.666856
5              CatBoost         0.6500      0.682576
6           Extra Trees         0.6325      0.670455
7     Gradient Boosting         0.6225      0.636111
8   Logistic Regression         0.5825      0.641414
9                   MLP         0.5875      0.642109
10        Random Forest         0.6275      0.675505
11     SVM (RBF kernel)         0.6250      0.726389
12              XGBoost         0.6350      0.683649
13  k-Nearest Neighbors         0.6350      0.661679
14             lightGBM         0.6175      0.652525

Average across models:

   Accuracy_Mean  ROC_AUC_Mean
0       0.607833      0.651073

In [77]:
print("Radiomics + demographic Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=False, use_demographic=True, file_name="center2_aggregated_results.json")

Radiomics + demographic Features:

                  model  Accuracy_Mean  ROC_AUC_Mean
0           transformer         0.6625      0.787879
1                   mil         0.6300      0.699495
2             deep_sets         0.6225      0.639899
3                 graph         0.6300      0.693939
4              AdaBoost         0.6800      0.848485
5              CatBoost         0.7125      0.847980
6           Extra Trees         0.7175      0.769949
7     Gradient Boosting         0.6650      0.797096
8   Logistic Regression         0.5875      0.634722
9                   MLP         0.6350      0.671402
10        Random Forest         0.7000      0.796023
11     SVM (RBF kernel)         0.6250      0.726389
12              XGBoost         0.6850      0.844571
13  k-Nearest Neighbors         0.6350      0.661679
14             lightGBM         0.6900      0.822664

Average across models:

   Accuracy_Mean  ROC_AUC_Mean
0         0.6585      0.749478

In [78]:
print("Radiomics + coords Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=True, use_demographic=False, file_name="center2_aggregated_results.json")

Radiomics + coords Features:

                  model  Accuracy_Mean  ROC_AUC_Mean
0           transformer         0.6200      0.708712
1                   mil         0.6150      0.635101
2             deep_sets         0.5400      0.534154
3                 graph         0.6275      0.609785
4              AdaBoost         0.6400      0.728030
5              CatBoost         0.6600      0.710606
6           Extra Trees         0.6375      0.675189
7     Gradient Boosting         0.6775      0.715278
8   Logistic Regression         0.5825      0.644444
9                   MLP         0.5950      0.646780
10        Random Forest         0.6625      0.694318
11     SVM (RBF kernel)         0.6250      0.726389
12              XGBoost         0.6500      0.731124
13  k-Nearest Neighbors         0.6350      0.661679
14             lightGBM         0.6475      0.728283

Average across models:

   Accuracy_Mean  ROC_AUC_Mean
0       0.627667      0.676658

In [79]:
print("Radiomics + demographic + coords Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph", "ml_models"], use_coords=True, use_demographic=True, file_name="center2_aggregated_results.json")

Radiomics + demographic + coords Features:

                  model  Accuracy_Mean  ROC_AUC_Mean
0           transformer         0.7075      0.811364
1                   mil         0.6700      0.741793
2             deep_sets         0.6775      0.753030
3                 graph         0.7075      0.784091
4              AdaBoost         0.6725      0.854167
5              CatBoost         0.7175      0.843687
6           Extra Trees         0.6975      0.782702
7     Gradient Boosting         0.7325      0.825000
8   Logistic Regression         0.5875      0.632955
9                   MLP         0.6625      0.739078
10        Random Forest         0.7250      0.817740
11     SVM (RBF kernel)         0.6250      0.726389
12              XGBoost         0.6850      0.845960
13  k-Nearest Neighbors         0.6350      0.661679
14             lightGBM         0.7025      0.831755

Average across models:

   Accuracy_Mean  ROC_AUC_Mean
0       0.680333      0.776759

# Test Time Adaptation (TTA) on Center 2 data

## TENT method for TTA

In [80]:
print("Radiomics + demographic + coords Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph"], use_coords=True, use_demographic=True, file_name="tta_tent_center2_aggregated_results.json")

Radiomics + demographic + coords Features:

         model  Accuracy_Mean  ROC_AUC_Mean
0  transformer         0.7075      0.868182
1          mil         0.7700      0.864141
2    deep_sets         0.7725      0.857702
3        graph         0.7150      0.802904

Average across models:

   Accuracy_Mean  ROC_AUC_Mean
0        0.74125      0.848232

## Norm method for TTA

In [81]:
print("Radiomics + demographic + coords Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph"], use_coords=True, use_demographic=True, file_name="tta_norm_center2_aggregated_results.json")

Radiomics + demographic + coords Features:

         model  Accuracy_Mean  ROC_AUC_Mean
0  transformer         0.7075      0.811364
1          mil         0.6700      0.741793
2    deep_sets         0.6775      0.753030
3        graph         0.7075      0.784091

Average across models:

   Accuracy_Mean  ROC_AUC_Mean
0       0.690625      0.772569

In [82]:
print("Radiomics + demographic  Features:")
load_results_table("../Results", ["transformer", "mil", "deep_sets", "graph"], use_coords=False, use_demographic=True, file_name="tta_tent_center2_aggregated_results.json")

Radiomics + demographic  Features:

         model  Accuracy_Mean  ROC_AUC_Mean
0  transformer         0.7050      0.871465
1          mil         0.7525      0.850884
2    deep_sets         0.7250      0.828788
3        graph         0.6575      0.776136

Average across models:

   Accuracy_Mean  ROC_AUC_Mean
0           0.71      0.831818